spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    changeLogFile: db/changelog/db:changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true # Показывать SQL-запросы в консоли
    logging:
      level:
        org.hibernate.SQL: DEBUG  # SQL запросы
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # ПАРАМЕТРЫ
    properties:
      hibernate:
        format_sql: true # Форматировать SQL для читаемости
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT}
