spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    changeLogFile: db/changelog/db:changelog-master2.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true # Показывать SQL-запросы в консоли
    properties:
      hibernate:
        format_sql: true # Форматировать SQL для читаемости
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master2.yaml

server:
  port: ${SERVER_PORT}
