spring:
  application:
    name: payment-service-app

  datasource: # объединяет в себе параметры подключения к БД
    url: jdbc:postgresql://localhost:5432/payment-db # URL подключения к БД
    username: admin # Имя пользователя
    password: secret # Пароль

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Показывать SQL-запросы в консоли
    properties:
      hibernate:
        format_sql: true # Форматировать SQL для читаемости

server:
  port: 8080
