name: Build Project for PR
on:
  # Запуск только при создании или обновлении pull request в ветку main
  pull_request:
    branches:
      - 'feature'
      - 'feature/**'
      - 'bugfix'
      - 'develop'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4
      # Шаг 2: Устанавливаем JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Шаг 3: Сборка Maven-проекта
      - name: Build with Maven
        run: ./mvnw clean install
